# Generated by Django 4.0.1 on 2024-10-04 15:25

from django.db import migrations, models
#from account.models import Profile
#from merchant.models import Seller

#def clean_invalid_following_data(apps, schema_editor):
 #   profile = apps.get_model("account", "Profile")
  #  seller = apps.get_model("merchant", "Seller")
#
 #   valid_seller_ids = Seller.objects.values_list("id", flat=True)

  #  for profile in Profile.objects.all():
   #     profile.following.set(profile.following.filter(id__in=valid_seller_ids))


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0023_seller_follower'),
      
        ('account', '0020_alter_profile_following'),
    ]

    operations = [
    #    migrations.RunPython(clean_invalid_following_data, migrations.RunPython.noop),
#        migrations.AlterField(
#            model_name='profile',
#            name='following',
#            field=models.ManyToManyField(blank=True, related_name='following_list', to='merchant.Seller'),
#        ),
    ]
